# Don't print a new line at the start of the prompt
add_newline = false

# Replace the "â¯" symbol in the prompt with "âœ"
[character]
success_symbol = "âœ(bold green) "
error_symbol = "[âœ—](bold red) "

format = """
$all\
$symbol
"""

[rlang]
detect_files = []

[python]
symbol = 'ğŸ‘¾ '
pyenv_version_name = true

